### ISSUE TITLE
Feedback to address

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/cli#100]
From a helpful feedback session with @martinagvilas

- [x] ~~When you build a book that has a config and toc file in the root, but *all* of the content in a sub-folder, then sphinx throws an error and says it can't find files w/ `rst`.~~ couldn't reproduce
  - Note - I wasn't able to reproduce this. @martinagvilas could you provide an example that we can use to recreate this?
- [x] In general most errors were Sphinx errors - it was confusing that the Sphinx errors have a "reach out to the sphinx devs" note in them. Fixed in #91 
- [x] It was hard / manual to convert the old `toc.yml` file to the new `toc.yml` file. fixed in #103 
- [x] The *first* page doesn't show up in the left sidebar, it is only reachable by clicking the logo. How can you get the first page to show up? Fixed in https://github.com/ExecutableBookProject/cli/pull/99
- [x] We don't document how to preview the file once the website is build. e.g. `chrome _build/html/index.html`. Fixed in #91 
- [x] Add back in the section on hosting online with netlify etc done in #101 
- [x] Some simple configuration options that were in the old jupyter book config file aren't in the new one
	- [x] Numbering sections to the left done in #101

**Comment by martinagvilas** [comment]
Hey 👋 I  was actually never able to reproduce number 1, so probably I was doing something wrong.

Related to number 3, I did persistently get this error: 

```
Exception occurred:
  File "/Users/martina.gonzales/cli/jupyter_book/toc.py", line 167, in update_indexname
    app.config["master_doc"] = _no_suffix(toc["file"])
KeyError: 'file'
```
... until I figured out that in the toc file I had forgotten to change one instance of `url:` (old jupyter-book format to define paths to the file) to `file:` (as the new jupyter-book requires). It took me a while to understand what the error was, so perhaps it can be improved to be more readable as I imagine many will have the same issue when upgrading the book.

**Comment by choldgraf** [comment]
@martinagvilas maybe in the interrim we should just support `url:` with a deprecation notice 🤔

**Comment by martinagvilas** [comment]
@choldgraf that would be even more user-friendly I think 😄

**Comment by choldgraf** [comment]
OK, with https://github.com/ExecutableBookProject/cli/pull/103 merged, I think we can now close this issue, all items are addressed! Thanks @martinagvilas for your feedback and for the PRs to some of these repos :-)
